name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build project
        id: build
        run: |
          make build
          echo "::set-output name=filename::$(ls dist)"
        shell: bash
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.filename }}
          path: ./dist/${{ steps.build.outputs.filename }}

  MacOS:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build project
        id: build
        run: |
          make build
          echo "::set-output name=filename::$(ls dist)"
        shell: bash
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.filename }}
          path: ./dist/${{ steps.build.outputs.filename }}

  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build project
        id: build
        run: |
          make build
          echo "::set-output name=filename::$((Get-ChildItem -Path "./dist" | Select-Object -First 1).Name)"
        shell: pwsh
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.filename }}
          path: ./dist/${{ steps.build.outputs.filename }}

  Release:
    needs: [Linux, MacOS, Windows]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Get version
        id: version
        run: |
          echo "::set-output name=version::$(make version)"
      - name: Download Linux release file
        uses: actions/download-artifact@master
        with:
          name: PROJECT_NAME-${{ steps.version.outputs.version }}-linux
          path: ./dist/PROJECT_NAME-${{ steps.version.outputs.version }}-linux
      - name: Download MacOS release file
        uses: actions/download-artifact@master
        with:
          name: PROJECT_NAME-${{ steps.version.outputs.version }}-darwin
          path: ./dist/PROJECT_NAME-${{ steps.version.outputs.version }}-darwin
      - name: Download Windows release file
        uses: actions/download-artifact@master
        with:
          name: PROJECT_NAME-${{ steps.version.outputs.version }}-win32.exe
          path: ./dist/PROJECT_NAME-${{ steps.version.outputs.version }}-win32.exe
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Linux release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/PROJECT_NAME-${{ steps.version.outputs.version }}-linux/PROJECT_NAME-${{ steps.version.outputs.version }}-linux
          asset_name: PROJECT_NAME-${{ steps.version.outputs.version }}-linux
          asset_content_type: application/octet-stream
      - name: Upload MacOS release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/PROJECT_NAME-${{ steps.version.outputs.version }}-darwin/PROJECT_NAME-${{ steps.version.outputs.version }}-darwin
          asset_name: PROJECT_NAME-${{ steps.version.outputs.version }}-darwin
          asset_content_type: application/octet-stream
      - name: Upload Windows release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/PROJECT_NAME-${{ steps.version.outputs.version }}-win32.exe/PROJECT_NAME-${{ steps.version.outputs.version }}-win32.exe
          asset_name: PROJECT_NAME-${{ steps.version.outputs.version }}-win32.exe
          asset_content_type: application/octet-stream
